### PR TITLE
small proposed changes to spec-v1

### PR DESCRIPTION
**Pull request by kwantam**
This PR more or less mirrors our out-of-band conversation about defining Hp, Hp2, etc., and proposes some other small tweaks.

### CODE REVIEW

**Comment by hoeteck** [comment]
Thanks, Riad! Two questions/comments about the pull request:

1. Suppose we instantiate hash_fn with SHA256. Then, sign(sk, msg) will end up calling

    `SHA256 (msg || I2OSP(0, 1)), SHA256 (msg || I2OSP(1, 1))`

(ignoring ciphersuite for now). If I understood you and Justin correctly, we want to avoid this because if msg (= input to sign) is long, then we'll have to compute SHA256 twice over a long msg.

2. We fixed the length of the ciphersuite to 8 bits to ensure unique decoding, so we shouldn't need to add len(msg) in

   `hashtoG1(msg || I2OSP(len(msg), 8) || ciphersuite)`

**Comment by kwantam** [comment]
Thanks for the comments!

1. Good point. Now I understand that this is the issue you were alluding to via email. So how about we add a "tweak" input to hash_to_field along the lines of what you proposed? And maybe it can be simple: just compute `msg' = hash_fn(msg) || tweak`

2. Understood. I will undo.

EDIT: pushed a response.

(Happy to squash commits etc)

**Comment by hoeteck** [comment]
Thanks a lot, Riad!

Let me also quickly explain our rationale for picking a 8-bit ciphersuite string:

1. the current hash-to-curve draft uses ASCII strings for cipher suites; this requires additionally fixing a way to convert ASCII strings to octet strings.

2. if we allow variable-length ciphersuite, then we'll need to append len(msg), and there's an additional choice to be made about where to put len(msg) (before or after msg?)

3. adding len(msg) creates ambiguity during signature verification. For many use cases, ciphersuite will be some fixed string. Then, I can imagine an (incorrect) implementation of signature verification that simply strips off ciphersuite and len(msg) to recover msg, but not check that len(msg) is correctly computed. This would ruin strong unforgeability.

**Comment by kwantam** [comment]
All of this makes a lot of sense.

Do you suppose it would be a good idea to try and close the loop on the `ciphersuite` representation with the hash-to-curve authors?

**Comment by hoeteck** [comment]
Yes, definitely a great idea! :)

**Pull request merged**
